version: "3.7"

volumes:
  code_review_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./docker/data/data
  code_review_db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./docker/data/db_data

networks:
  code_review:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.21.0.0/24

services:
##################################### DEPENDS #####################################
  code_review_db:
    container_name: code_review_db
    image: mariadb:10.3
    restart: on-failure
    volumes:
      - code_review_db_data:/var/lib/mysql
    networks:
      - code_review
    ports:
      - 33060:3306
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_review_1

##################################### WEB #####################################
  code_review_nginx:
    container_name: code_review_nginx
    image: nginx:latest
    restart: on-failure
    depends_on:
      - code_review_php74_fpm
    ports:
      - "8180:80"
    volumes:
      - ../:/var/www/code_review
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - code_review_data:/data
    networks:
      - code_review

  code_review_php74_fpm:
    container_name: code_review_php74_fpm
    image: code_review-php74-fpm:latest
    restart: on-failure
    user: "1000:1000"
    build:
      dockerfile: dockerfile/php74-fpm
      context: ./
    depends_on:
      - code_review_db
    volumes:
      - ../:/var/www/code_review
      - ./configs/php74.ini:/etc/php/7.4/fpm/conf.d/99-code_review.ini
      - ./configs/php74.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - code_review_data:/data
    networks:
      - code_review
